<?php /** @var Snowcore_Subscriber_Block_Newsletter_Additional $this */ ?>
<div class="input-box">
    <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="firstname" class="input-text required-entry" placeholder="First name" />
</div>
<div class="input-box">
    <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="lastname" class="input-text required-entry" placeholder="Last name"/>
</div>